import argparse
import wdtw_dl 

site_url = "https://osricrpg.com/wizardawn/"

desc = "Create a PNG of a worldmap generated by "+site_url
parser = argparse.ArgumentParser(description=desc)
parser.add_argument('-o','--output', type=str,
        default="merged.png",
        help="the name of the output image")
parser.add_argument('-d','--directory', type=str,
        default="./images/",
        help="the root of the image directory to use")
parser.add_argument('-i','--input', type=str,
        default="",
        help="path to an input file to use instead of making a request")

args = parser.parse_args()
args.site = site_url
# some checks
if (args.directory[-1] != '/'):
    args.directory += '/'

if __name__ == "__main__":
    wdtw_dl.main(args)
